language: rust
rust:
  - stable
  - nightly
env:
  - NEAR_RELEASE=true
  - NEAR_RELEASE=false

before_install:
  - rm rust-toolchain
  - cargo install twiggy

before_script:
  - rustup target add wasm32-unknown-unknown

script:
  - ./ci-test.sh
